# Generated by Django 4.1.7 on 2023-03-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uniapp', '0002_asignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=3)),
                ('asignatura_id', models.IntegerField()),
                ('docente_id', models.IntegerField()),
                ('horario', models.CharField(max_length=30)),
                ('estudiante_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
    ]
