# Generated by Django 4.1.7 on 2023-04-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uniapp', '0003_docente_estudiante_grupo_delete_estudiantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='clave',
            new_name='carrera',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='estudiante_id',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='clave',
        ),
    ]
